### ISSUE TITLE
Loop scheduling missing MSTORE/jump dependency

### ISSUE THREAD

**Issue by Chippiewill** [ktok07b6/polyphony#9]
I have a custom array interface implementation that takes 4 steps to complete a write (rather than the default of 2), I'm having issues where if I use it in a loop the the last 2 steps get truncated. I've changed the n_step being used to 4 and the increased the latency of MSTORE and I've traced it back to an issue in the scheduler. It appears that the jump in the forbody back to the fortest does not depend on mstores in the loop body:

Here's the schedule for the block:
```
Node 6046 0 0:0 @cond565:bool = (i#2:int[32] < @t560:int[32]) @top.const_multiply_fortest2
Node 608c 1 0:1 cjump @cond565:bool ? @top.const_multiply_forbody3, @top.const_multiply_forelse5 @top.const_multiply_fortest2
Node ba6a 0 0:3 @t566:int[32] = ys:list[int[32]][i#2:int[32]] @top.const_multiply_forbody3
Node 459a 0 0:0 i#3:int[32] = (i#2:int[32] + 0x1) @top.const_multiply_forbody3
Node ba5c 1 3:3 t:int[32] = (@t566:int[32] * x:int[32]) @top.const_multiply_forbody3
Node ba4e 2 3:6 mstore(ys:list[int[32]][i#2:int[32]], t:int[32]) @top.const_multiply_forbody3
Node bacc 3 3:4 i#2:int[32] = i#3:int[32] @top.const_multiply_forbody3
Node 45af 4 4:5 jump @top.const_multiply_fortest2 'L' @top.const_multiply_forbody3
```

You can see that the mstore ends on state 6 but the jump back begins on state 4. The state reducer then removes states 5, 6 because they can't be reached.

**Comment by Chippiewill** [comment]
There also appears to be a slightly more subtle issue which is the loop counter `i` gets updated in the same state that it gets used by mstore which causes issues if the first step of the mstore uses a meta_wait or the loop counter is used in a later state.

**Comment by ktok07b6** [comment]
Thanks for reporting, it should be fixed now.
**https://github.com/ktok07b6/polyphony/commit/907732f8b1b6927b555c559256fa9659a3f06d1e**
You can specify your own memory latency like following.

```
$ polyphony -c '{"internal_ram_store_latency":3}' your_source.py
```
